### ISSUE TITLE
Crash if address does not have a ZIP from geocoder API

### ISSUE THREAD

**Issue by phobozad** [enkur/ATT-Fiber-Check#13]
If an address is returned from the geocoder API without a ZIP code, the test_address function crashes the address.py script with an IndexError exception.

The line that causes this is:
```
addr = ("%s,%s,%s"%(l[0],l[1].strip(),l[2].split()[1]))
```

A quick and dirty fix is to catch IndexError exceptions in the try and simply return "None", which looks to indicate to the caller that the coordinates do not correspond to a valid address.

```
    except GeocoderError as e:
        print("error: ", e.args)
        return e.args
    except IndexError:
        #Probably missing zip code
        return None
```

The following coordinates will exhibit this behavior due to the geocoding API not returning a ZIP code:
```
43.237341903863516, -88.1495279038634
```

**Comment by enkur** [comment]
Ill try to get that fixed tonight.

**Comment by enkur** [comment]
This is resolved.
